"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"

#right_format = "$time"

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = '[>](bold green)'

[git_metrics]
disabled = false


[package]
disabled = true

[python]
disabled = true
